### ISSUE TITLE
Compile error with git HEAD

### ISSUE THREAD

**Issue by tonycurtis** [openpmix/openpmix#3026]
## Background information

Compiling latest code, get errors

### What version of the PMIx Reference Library are you using? 

master @ c43e3bfbecb78deb631361dcee61b0e438918c20

### Describe how PMIx was installed 

git clone

### Please describe the system on which you are running

* Operating system/version: Fedora 38 (beta)
* Computer hardware: x86/arm
* Network type: TCP

GCC 13.0.1.  N.B. This is on a test machine with beta-release OS, but hopefully is a heads-up.

-----------------------------

## Details of the problem

```
Making all in util
make[2]: Entering directory '/home/tc/src/pmix/build/src/util'
depbase=`echo pmix_if.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../pmix-git/src/util -I../../src/include -I../../include   -iquote/home/tc/src/pmix/build -iquote/home/tc/src/pmix/pmix-git -iquote/home/tc/src/pmix/pmix-git/src -iquote/home/tc/src/pmix/build/include -I/home/tc/src/pmix/pmix-git/include    -O3 -DNDEBUG  -finline-functions  -fvisibility=hidden -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -Wshadow -Werror-implicit-function-declaration -fno-strict-aliasing -pedantic -Wall -Wextra -Werror -MT pmix_if.lo -MD -MP -MF $depbase.Tpo -c -o pmix_if.lo ../../../pmix-git/src/util/pmix_if.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../pmix-git/src/util -I../../src/include -I../../include -iquote/home/tc/src/pmix/build -iquote/home/tc/src/pmix/pmix-git -iquote/home/tc/src/pmix/pmix-git/src -iquote/home/tc/src/pmix/build/include -I/home/tc/src/pmix/pmix-git/include -O3 -DNDEBUG -finline-functions -fvisibility=hidden -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -Wshadow -Werror-implicit-function-declaration -fno-strict-aliasing -pedantic -Wall -Wextra -Werror -MT pmix_if.lo -MD -MP -MF .deps/pmix_if.Tpo -c ../../../pmix-git/src/util/pmix_if.c  -fPIC -DPIC -o .libs/pmix_if.o
../../../pmix-git/src/util/pmix_if.c: In function 'pmix_ifnametoaddr':
../../../pmix-git/src/util/pmix_if.c:93:13: error: 'strcmp' reading 1 or more bytes from a region of size 0 [-Werror=stringop-overread]
   93 |         if (strcmp(intf->if_name, if_name) == 0) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: note: source object is likely at address zero
../../../pmix-git/src/util/pmix_if.c: In function 'pmix_ifnametoindex':
../../../pmix-git/src/util/pmix_if.c:113:13: error: 'strcmp' reading 1 or more bytes from a region of size 0 [-Werror=stringop-overread]
  113 |         if (strcmp(intf->if_name, if_name) == 0) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: note: source object is likely at address zero
../../../pmix-git/src/util/pmix_if.c: In function 'pmix_ifnametokindex':
../../../pmix-git/src/util/pmix_if.c:132:13: error: 'strcmp' reading 1 or more bytes from a region of size 0 [-Werror=stringop-overread]
  132 |         if (strcmp(intf->if_name, if_name) == 0) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: note: source object is likely at address zero
cc1: all warnings being treated as errors
make[2]: *** [Makefile:889: pmix_if.lo] Error 1
```

**Comment by rhc54** [comment]
Huh - that's a new one. I'm not even sure what that means, so I'll have to do some digging to find out.

**Comment by tonycurtis** [comment]
BTW it builds ok with clang 15.0.7.  Might be a bledding-edge gcc problem?

**Comment by rhc54** [comment]
Could be - still worth at least a look.

**Comment by rhc54** [comment]
I checked around on the web and found people reporting this problem for sparc64. The gcc team said it was correct and intentional - means that you are referencing an address beyond the end of a field. However, I can't see that here, so I'm a bit at a loss.

Sadly, I don't seem to have gcc v13 as an option on my machine - hasn't been ported to the Mac yet. I'm going to take a stab at it being an issue where the length of `if_name` is non-limited while the length of `intf->if_name` is fixed - so I'm going to change `strcmp` to `strncmp` and ensure we cannot run too far, even though we do set that field in the struct to be NULL terminated.

Other than that, I have no earthly clue. Could be a bug in gcc 13 as the prior report for sparc64 clearly did reference outside their passed structure and we don't. Not sure where to go if this try doesn't work. Can you please give https://github.com/openpmix/openpmix/pull/3030 a try?

**Comment by tonycurtis** [comment]
I was going to suggest the `strncmp` change.  I'll give it a poke.

**Comment by tonycurtis** [comment]
I think it's a bug: how can `strncmp` know at compile-time what's going to be in some `if_name` field?

**Comment by tonycurtis** [comment]
Well, `if_name` is a `char [] so the following compiles:

```
     93         if ( *(intf->if_name) != '\0' ) {
     94             if (strncmp(intf->if_name, if_name, PMIX_IF_NAMESIZE-1) == 0     94 ) {
     95                 return intf->if_index;
     96             }
     97         }
```

**Comment by rhc54** [comment]
Wow - now that is bizarre. `intf->if_name` is a fixed-size character array. So I guess they are saying that we have to protect against the array being all `NULL`??? I thought `strcmp` could handle zero-length strings so long as the pointer to the string wasn't NULL.

Feels like a bug to me - yes?

**Comment by tonycurtis** [comment]
I think so too.  Not 100% sure but I do get that "feel"

**Comment by rhc54** [comment]
FWIW: I thought they were worrying about the `if_name` field being NULL (not the `intf->if_name` field).

For now, I'll add that check to shut them up.

**Comment by tonycurtis** [comment]
I tried the `if_name` variable too, and same `strncmp` complaint.  Notice the error is

"error: 'strncmp' specified bound 255 exceeds **source size 0**"

so gcc obviously seems to think the `intf->if_name` is empty in some fashion

**Comment by rhc54** [comment]
Strange - yet it doesn't complain about this line?
```c
            if (0 == strcmp(ipv4, "localhost") || 0 == strcmp(ipv4, "127.0.0.1")) {
```
`ipv4` is a fixed size array - I wonder why it doesn't complain here?

**Comment by tonycurtis** [comment]
Something to do with your list iterator obscuring intent?

**Comment by rhc54** [comment]
I guess that's as good a theory as any! 🤷‍♂️
