### ISSUE TITLE
Cannot compile with Intel 2021.6

### ISSUE THREAD

**Issue by albandil** [openpmix/openpmix#2732]
I downloaded the current development version from the repository and tried to build with Intel suite.
```
$ git clone https://github.com/openpmix/openpmix.git openpmix-git
$ cd openpmix-git
$ git rev-parse HEAD
0c94393c332f624ae533144b622795acef604d67
$ ./autogen.pl
$ mkdir build
$ cd build
$ . /opt/intel/oneapi/setvars.sh
$ icc --version
icc (ICC) 2021.6.0 20220226
Copyright (C) 1985-2022 Intel Corporation.  All rights reserved.

$../configure CC=icc CXX=icpc FC=ifort
$ make V=1
```
The compilation fails in files where `int` and various `enum` types are combined shamelessly. One example here:
```
libtool: compile:  icc -DHAVE_CONFIG_H -I. -I../../../src/util -I../../src/include -I../../include -iquote/scratch.ssd/software/openpmix-git/build -iquote/scratch.ssd/software/openpmix-git -iquote/scratch.ssd/software/openpmix-git/src -iquote/scratch.ssd/software/openpmix-git/build/include -I/scratch.ssd/software/openpmix-git/include -I/usr/include/libxml2 -O3 -DNDEBUG -finline-functions -restrict -pthread -fvisibility=hidden -Wundef -Wno-long-long -Wsign-compare -Wmissing-prototypes -Wstrict-prototypes -Wcomment -Wshadow -Werror-implicit-function-declaration -fno-strict-aliasing -pedantic -Wall -Wextra -Werror -MT pmix_keyval_parse.lo -MD -MP -MF .deps/pmix_keyval_parse.Tpo -c ../../../src/util/pmix_keyval_parse.c  -fPIC -DPIC -o .libs/pmix_keyval_parse.o
../../../src/util/pmix_keyval_parse.c(103): error #188: enumerated type mixed with another type
                  parse_line_new(filename, val, callback);
                                           ^

../../../src/util/pmix_keyval_parse.c(328): error #188: enumerated type mixed with another type
              val = pmix_util_keyval_yylex();
                  ^

../../../src/util/pmix_keyval_parse.c(347): error #188: enumerated type mixed with another type
              val = pmix_util_keyval_yylex();
                  ^

../../../src/util/pmix_keyval_parse.c(364): error #188: enumerated type mixed with another type
          val = pmix_util_keyval_yylex();
              ^

compilation aborted for ../../../src/util/pmix_keyval_parse.c (code 2)
```
This affects also the 5.0.x branch of Open MPI.

**Comment by albandil** [comment]
Thanks a lot, using `--disable-devel-check` works like a charm! It didn't occur to me that there could be a different compiler setup for a git clone and for a distribution tarball, but I agree that it makes sense.

Now that the oneAPI compilers are freely available, I think they are becoming quite popular.

**Comment by rhc54** [comment]
Yeah, this is a bit of a problem. Flex generates the parsing file, and the Flex `yylex` generated program returns an `int`. We have no control over that - that's what Flex does.

Flex also uses a lookup table to determine the return constant - and that uses an `enum`.

So at some point, you have an `int` that has to become an `enum`. Given that this compiler seems to be the only one that cares, it will be a hit/miss project to find what it will accept without making the other compilers complain. But I'll give it a try or two before giving up.

As to the popularity of the oneAPI compilers - we'll have to wait and see. I suspect it will largely depend on how the CPU wars progress. 🤷‍♂️ Way outside the scope of this project 😄

**Comment by rhc54** [comment]
This is a really simple patch - would you mind applying it and retrying the `--enable-devel-check` option?
```diff
diff --git a/src/util/pmix_keyval_parse.c b/src/util/pmix_keyval_parse.c
index 4866617..cc4e4d1 100644
--- a/src/util/pmix_keyval_parse.c
+++ b/src/util/pmix_keyval_parse.c
@@ -67,7 +67,7 @@ int pmix_util_keyval_parse(const char *filename, pmix_keyval_parse_fn_t callback
 {
     int val;
     int ret = PMIX_SUCCESS;
-    ;
+    pmix_keyval_parse_state_t state;
 
     pmix_mutex_lock(&keyval_mutex);
 
@@ -100,7 +100,8 @@ int pmix_util_keyval_parse(const char *filename, pmix_keyval_parse_fn_t callback
             case PMIX_UTIL_KEYVAL_PARSE_MCAVAR:
             case PMIX_UTIL_KEYVAL_PARSE_ENVVAR:
             case PMIX_UTIL_KEYVAL_PARSE_ENVEQL:
-                parse_line_new(filename, val, callback);
+                state = val;
+                parse_line_new(filename, state, callback);
                 break;
 
             default:
```

**Comment by hppritcha** [comment]
I was able to reproduce this.  The patch only helps to get further.  I think if building from clone the --disable-devel-check is an okay workaround for this compiler. 

Actually @albandil is using the Intel classic compiler, which is soon going to go into maintenance mode (end of this year is what we're being told).  

I tried using the intel 2022.1.0 release of the oneapi compiler and master branch compiles without incident.

./configure CC=icx CXX=icpx --prefix=$PWD/install_oneapi

**Comment by albandil** [comment]
> (...) the Intel classic compiler, which is soon going to go into maintenance mode (end of this year is what we're being told).
> 
> I tried using the intel 2022.1.0 release of the oneapi compiler and master branch compiles without incident.

Then there is indeed little use in trying to fix this issue. The patch would unfortunately need to be significantly longer than https://github.com/openpmix/openpmix/issues/2732#issuecomment-1234341465. In light of the new information, I think the issue can be closed.

**Comment by rhc54** [comment]
Agreed - thx both of you for the input!
