### ISSUE TITLE
PMIx compile with really old hwloc (e.g. 1.11) blows up

### ISSUE THREAD

**Issue by tonycurtis** [openpmix/openpmix#2057]
## Background information

PMIx git compile blows up when using really old hwloc package

### What version of the PMIx Reference Library are you using? 

github master @ 81bec81b67206f1b96e679d6ef932ce3c8b1e54a

### Describe how PMIx was installed 

clone

### Please describe the system on which you are running

* Operating system/version: Ubuntu 18.04
* Computer hardware: x86
* Network type: (n/a)

-----------------------------

## Details of the problem

Ubuntu 18.04 provides hwloc 1.11.9:

```
make[2]: Entering directory '/home/arcurtis/src/pmix/build/src/mca/ploc/hwloc'
  CC       ploc_hwloc_component.lo
  CC       ploc_hwloc.lo
../../../../../pmix-git/src/mca/ploc/hwloc/ploc_hwloc.c: In function ‘setup_topology’:
../../../../../pmix-git/src/mca/ploc/hwloc/ploc_hwloc.c:574:66: error: ‘HWLOC_VERSION’ undeclared (first use in this function); did you mean ‘_SC_VERSION’?
         pmix_asprintf(&pmix_globals.topology.source, "hwloc:%s", HWLOC_VERSION);
                                                                  ^~~~~~~~~~~~~
                                                                  _SC_VERSION
../../../../../pmix-git/src/mca/ploc/hwloc/ploc_hwloc.c:574:66: note: each undeclared identifier is reported only once for each function it appears in
Makefile:837: recipe for target 'ploc_hwloc.lo' failed
```

```
$ dpkg -s hwloc
Package: hwloc
Status: install ok installed
Priority: optional
Section: admin
Installed-Size: 598
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: foreign
Version: 1.11.9-1
...
...
```

Compiles fine with locally installed hwloc 2.0 ++
